version: '3.1'
services:
  master:
    image: mysql:5.6
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql_master
    volumes:
      - ./initdb/users.sql:/docker-entrypoint-initdb.d/users.sql
      - ./initdb/create_replication_user.sql:/docker-entrypoint-initdb.d/create_replication_user.sql
      - ./conf/binlog.cnf:/etc/mysql/mysql.conf.d/binlog.cnf
    ports:
      - 3306:3306
    env_file:
    - .env

    networks:
      - main
  slave:
    image: mysql:5.6
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    depends_on: 
      - master
    container_name: mysql_slave
    volumes:
      - ./initdb/users.sql:/docker-entrypoint-initdb.d/users.sql
      - ./initdb/enable_replication.sql:/docker-entrypoint-initdb.d/enable_replication.sql
      - ./conf/slave.cnf:/etc/mysql/mysql.conf.d/slave.cnf
    ports:
      - 3307:3306
    env_file:
    - .env
    networks:
      - main
  proxysql:
    image: severalnines/proxysql:2.0
    restart: unless-stopped
    container_name: proxysql
    volumes:
      - ./conf/proxysql.cnf:/etc/proxysql.cnf
    ports:
      - 6033:6033
      - 6032:6032
      - 6080:6080
    networks:
      - main
networks:
  main: